<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>George-W-Bush_Square.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="George-W-Bush.jpg" />
    <None Remove="George-W-Bush_Square.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="George-W-Bush_Square.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="George-W-Bush.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="George-W-Bush_Square.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
